### ISSUE TITLE
AutoPinEdgeToSuperviewEdge not working

### ISSUE THREAD

**Issue by ryderjack** [smileyborg/PureLayout#62] opened 2015-04-17 23:44 UTC
Hi,

Since updating xcode to 6.3 and iOS to 8.3 the following constraints just aren't working for me:

```Objective-C
[self.prefsView autoPinEdgeToSuperviewEdge:ALEdgeTop withInset:(self.navigationController.navigationBar.frame.size.height )];
 [self.prefsView autoPinEdgeToSuperviewEdge:ALEdgeLeft];
[self.prefsView autoPinEdgeToSuperviewEdge:ALEdgeRight];
```

The view I'm using these on just isn't visible when these are enabled

**Comment by liuxuan30** [comment] 2015-04-20 02:28
Have you checked if the constraints have been installed?
First of all, make sure you can see your autoPinEdgeToSuperviewEdge layouts in `self.prefsView.constraints`
check if your view has been added, and from my experience, view debugging feature in Xcode can help a lot.

**Comment by smileyborg** [comment] 2015-04-20 16:01
Hi @ryderjack,

You'll need to provide more information on what is happening, and preferably a small sample project to reproduce the issue, if you want help debugging this. I can tell you that the issue almost certainly doesn't have to do with PureLayout, since nothing has changed around this recently and I've seen no other reports of any issues. So it's probably something specific to your project, or maybe a general auto layout issue.

**Comment by expkzb** [comment] 2015-04-21 01:25
@ryderjack 
Your view doesn't have a constraint for "height".
And you can rewrite your first constraint with
```
 - (NSLayoutConstraint *)autoPinToTopLayoutGuideOfViewController:(UIViewController *)viewController withInset:(CGFloat)inset
```

**Comment by hamdan** [comment] 2015-04-24 12:20
after  updating xcode to 6.3 constraints just aren't working. same issue

**Comment by smileyborg** [comment] 2015-04-24 15:07
Hi @hamdan,

Are you able to reproduce the issue using the PureLayout example project/demos? Are you compiling against the iOS 8.3 Base SDK in Xcode 6.3? What version of iOS are you running on where you see this issue? Is this the simulator or device (which device, if so)?

I know that Apple has changed Auto Layout as of iOS 8.3, I don't know all the details but there was at least one significant bug fix that made it in to the release. So that could be causing the problem(s).

However, I don't see any issues myself, so if you're looking for help figuring out what is happening you'll need to provide more info.

**Comment by smileyborg** [comment] 2015-04-24 15:10
PureLayout's unit tests are also passing on iOS 8.3/Xcode 6.3.1, so if there is some issue at hand, let's make sure to write new tests to cover it.

**Comment by ryderjack** [comment] 2015-04-24 15:10
Apologies for the delay, I'm using the latest versions of Xcode and iOS. It's just odd that the constraints worked before updating my xcode

**Comment by smileyborg** [comment] 2015-04-24 18:00
@ryderjack As I've mentioned, I'm going to need more information to help figure out what is going on.

**Comment by liuxuan30** [comment] 2015-04-25 02:17
@ryderjack could you paste your view's constraints from lldb?

**Comment by hamdan** [comment] 2015-04-25 11:43
smileyborg  i am using xcode 6.3.1  ios sdk 8.3 ....  code work fine in device but in simulator its not working .  In previous version of xcode 6.1.1 its work perfectly on both simulator and device .
   On xcode 6.3.1 simulator no warning occurs while debug i am using this line of code

 
       [UIView autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblSchoolName autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblSchoolName autoPinEdgeToSuperviewEdge:ALEdgeTop withInset:kLabelVerticalInsets];
        [self.lblSchoolName autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:kLabelHorizontalInsets];
        [self.lblSchoolName autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:kLabelHorizontalInsets];
        
        
        [self.lblStreetAddress autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.lblSchoolName withOffset:kLabelVerticalInsets];
        
        [UIView autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblStreetAddress autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblStreetAddress autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:kLabelHorizontalInsets];
        [self.lblStreetAddress autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:kLabelHorizontalInsets];
        
        [self.lblAddress autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.lblStreetAddress withOffset:kLabelVerticalInsets];
        
        [UIView autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblAddress autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblAddress autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:kLabelHorizontalInsets];
        [self.lblAddress autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:kLabelHorizontalInsets];
        
        
        
        [self.lblCountyName autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.lblAddress withOffset:kLabelVerticalInsets];
        
        [UIView autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblCountyName autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblCountyName autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:kLabelHorizontalInsets];
        [self.lblCountyName autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:kLabelHorizontalInsets];
        
        
        [self.lblZipCode autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.lblCountyName withOffset:kLabelVerticalInsets];
        
        [UIView autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblZipCode autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblZipCode autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:kLabelHorizontalInsets];
        [self.lblZipCode autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:kLabelHorizontalInsets];
        
        
        [self.lblStateCountry autoPinEdge:ALEdgeTop toEdge:ALEdgeBottom ofView:self.lblZipCode withOffset:kLabelVerticalInsets];
        
        
        [UIView autoSetPriority:UILayoutPriorityRequired forConstraints:^{
            [self.lblStateCountry autoSetContentCompressionResistancePriorityForAxis:ALAxisVertical];
        }];
        [self.lblStateCountry autoPinEdgeToSuperviewEdge:ALEdgeLeading withInset:kLabelHorizontalInsets];
        [self.lblStateCountry autoPinEdgeToSuperviewEdge:ALEdgeTrailing withInset:kLabelHorizontalInsets];
        [self.lblStateCountry autoPinEdgeToSuperviewEdge:ALEdgeBottom withInset:kLabelVerticalInsets];

**Comment by hamdan** [comment] 2015-04-25 12:02
Xcode 6.3.1:

*UIWindow:0x78922dc0 - AMBIGUOUS LAYOUT
|   *UITransitionView:0x787f7c30
|   |   UILayoutContainerView:0x787ddc00
|   |   |   UINavigationTransitionView:0x787ed470
|   |   |   |   UIViewControllerWrapperView:0x78638d70
|   |   |   |   |   •UIView:0x786317b0
|   |   |   |   |   |   *UIImageView:0x78908c30
|   |   |   |   |   |   *UISearchBar:0x78903d60
|   |   |   |   |   |   |   UIView:0x78907ce0
|   |   |   |   |   |   |   |   UISearchBarBackground:0x78908e20
|   |   |   |   |   |   |   |   UISearchBarTextField:0x78903970
|   |   |   |   |   |   |   |   |   _UISearchBarSearchFieldBackgroundView:0x78e0d590
|   |   |   |   |   |   |   |   |   UIFieldEditor:0x79874600
|   |   |   |   |   |   |   |   |   |   _UIFieldEditorContentView:0x787b4ca0
|   |   |   |   |   |   |   |   |   |   |   UITextSelectionView:0x787f1c00
|   |   |   |   |   |   |   |   |   |   |   |   UIView:0x78e19460
|   |   |   |   |   |   |   |   |   |   UIImageView:0x787f25a0
|   |   |   |   |   |   |   |   |   |   UIImageView:0x787f1fc0
|   |   |   |   |   |   |   |   |   UIButton:0x787ef3e0
|   |   |   |   |   |   |   |   |   |   UIImageView:0x78f25920
|   |   |   |   |   |   |   |   |   UIImageView:0x78e0d290
|   |   |   |   |   |   *UILabel:0x78631cb0'Enter your school name an...'
|   |   |   |   |   |   *UIButton:0x78904d20'Can`t find my school''
|   |   |   |   |   |   |   UIButtonLabel:0x787ecf20'Can`t find my school''
|   |   |   |   |   |   *UIButton:0x78903420'Find my school'
|   |   |   |   |   |   |   UIButtonLabel:0x787eaf10'Find my school'
|   |   |   |   |   |   *UITableView:0x7907d800
|   |   |   |   |   |   |   UITableViewWrapperView:0x7907dc00
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x78e2cde0'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x78e2d160
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2cbe0- AMBIGUOUS LAYOUT for UILabel:0x78e2cbe0.minY{id: 2208}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2b490'101 WINDY WALKWAY'- AMBIGUOUS LAYOUT for UILabel:0x78e2b490'101 WINDY WALKWAY'.minY{id: 2201}, UILabel:0x78e2b490'101 WINDY WALKWAY'.Height{id: 2160}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2c520'ALEUTIANS EAST BOROUGH'- AMBIGUOUS LAYOUT for UILabel:0x78e2c520'ALEUTIANS EAST BOROUGH'.minY{id: 2215}, UILabel:0x78e2c520'ALEUTIANS EAST BOROUGH'.Height{id: 2166}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2c750'AK U.S.A'- AMBIGUOUS LAYOUT for UILabel:0x78e2c750'AK U.S.A'.minY{id: 2229}, UILabel:0x78e2c750'AK U.S.A'.Height{id: 2172}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2c200'99612'- AMBIGUOUS LAYOUT for UILabel:0x78e2c200'99612'.minY{id: 2222}, UILabel:0x78e2c200'99612'.Height{id: 2178}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2b190'KING COVE SCHOOL'- AMBIGUOUS LAYOUT for UILabel:0x78e2b190'KING COVE SCHOOL'.Height{id: 2184}
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78e2f300
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f3db10
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x78f3be70'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x78f3c080
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f3c150- AMBIGUOUS LAYOUT for UILabel:0x78f3c150.minY{id: 2092}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7880cf20'5586 KINTERBISH 10'- AMBIGUOUS LAYOUT for UILabel:0x7880cf20'5586 KINTERBISH 10'.minY{id: 2085}, UILabel:0x7880cf20'5586 KINTERBISH 10'.Height{id: 2044}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7880d250'SUMTER COUNTY'- AMBIGUOUS LAYOUT for UILabel:0x7880d250'SUMTER COUNTY'.minY{id: 2099}, UILabel:0x7880d250'SUMTER COUNTY'.Height{id: 2050}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f3c730'AL U.S.A'- AMBIGUOUS LAYOUT for UILabel:0x78f3c730'AL U.S.A'.minY{id: 2113}, UILabel:0x78f3c730'AL U.S.A'.Height{id: 2056}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f3cac0'36907'- AMBIGUOUS LAYOUT for UILabel:0x78f3cac0'36907'.minY{id: 2106}, UILabel:0x78f3cac0'36907'.Height{id: 2062}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7880d370'KINTERBISH JR HIGH SCHOOL'- AMBIGUOUS LAYOUT for UILabel:0x7880d370'KINTERBISH JR HIGH SCHOOL'.Height{id: 2068}
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7880e230
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78e2d470
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x78f36170'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x78f36380
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f36450- AMBIGUOUS LAYOUT for UILabel:0x78f36450.minY{id: 1976}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e29470'615 NORTH PINE ST'- AMBIGUOUS LAYOUT for UILabel:0x78e29470'615 NORTH PINE ST'.minY{id: 1969}, UILabel:0x78e29470'615 NORTH PINE ST'.Height{id: 1928}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2e920'LAUDERDALE COUNTY'- AMBIGUOUS LAYOUT for UILabel:0x78e2e920'LAUDERDALE COUNTY'.minY{id: 1983}, UILabel:0x78e2e920'LAUDERDALE COUNTY'.Height{id: 1934}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f36940'AL U.S.A'- AMBIGUOUS LAYOUT for UILabel:0x78f36940'AL U.S.A'.minY{id: 1997}, UILabel:0x78f36940'AL U.S.A'.Height{id: 1940}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f36ce0'35632'- AMBIGUOUS LAYOUT for UILabel:0x78f36ce0'35632'.minY{id: 1990}, UILabel:0x78f36ce0'35632'.Height{id: 1946}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f370f0'KILBY LABORATORY SCHOOL'- AMBIGUOUS LAYOUT for UILabel:0x78f370f0'KILBY LABORATORY SCHOOL'.Height{id: 1952}
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f37bf0
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f3b710
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x78f30f50'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x78f31160
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f31230- AMBIGUOUS LAYOUT for UILabel:0x78f31230.minY{id: 1860}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f316e0'115 COLLEGE ST SW'- AMBIGUOUS LAYOUT for UILabel:0x78f316e0'115 COLLEGE ST SW'.minY{id: 1853}, UILabel:0x78f316e0'115 COLLEGE ST SW'.Height{id: 1812}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f31ac0'CALHOUN COUNTY'- AMBIGUOUS LAYOUT for UILabel:0x78f31ac0'CALHOUN COUNTY'.minY{id: 1867}, UILabel:0x78f31ac0'CALHOUN COUNTY'.Height{id: 1818}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e296e0'AL U.S.A'- AMBIGUOUS LAYOUT for UILabel:0x78e296e0'AL U.S.A'.minY{id: 1881}, UILabel:0x78e296e0'AL U.S.A'.Height{id: 1824}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e27280'36265'- AMBIGUOUS LAYOUT for UILabel:0x78e27280'36265'.minY{id: 1874}, UILabel:0x78e27280'36265'.Height{id: 1830}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78e2b720'KITTY STONE ELEM SCHOOL'- AMBIGUOUS LAYOUT for UILabel:0x78e2b720'KITTY STONE ELEM SCHOOL'.Height{id: 1836}
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78e20440
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f34da0
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x78f27ca0'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x78f27eb0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f27f80- AMBIGUOUS LAYOUT for UILabel:0x78f27f80.minY{id: 1744}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f1d320'201 COLLEGE ST'- AMBIGUOUS LAYOUT for UILabel:0x78f1d320'201 COLLEGE ST'.minY{id: 1737}, UILabel:0x78f1d320'201 COLLEGE ST'.Height{id: 1696}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f29f00'COFFEE COUNTY'- AMBIGUOUS LAYOUT for UILabel:0x78f29f00'COFFEE COUNTY'.minY{id: 1751}, UILabel:0x78f29f00'COFFEE COUNTY'.Height{id: 1702}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f29e00'AL U.S.A'- AMBIGUOUS LAYOUT for UILabel:0x78f29e00'AL U.S.A'.minY{id: 1765}, UILabel:0x78f29e00'AL U.S.A'.Height{id: 1708}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f2c150'36453'- AMBIGUOUS LAYOUT for UILabel:0x78f2c150'36453'.minY{id: 1758}, UILabel:0x78f2c150'36453'.Height{id: 1714}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f28ce0'KINSTON SCHOOL'- AMBIGUOUS LAYOUT for UILabel:0x78f28ce0'KINSTON SCHOOL'.Height{id: 1720}
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f2cc10
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f306b0
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x78f13a80'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x78f13c90
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f13d60- AMBIGUOUS LAYOUT for UILabel:0x78f13d60.minY{id: 1628}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f14630'1328 28TH ST NORTH'- AMBIGUOUS LAYOUT for UILabel:0x78f14630'1328 28TH ST NORTH'.minY{id: 1621}, UILabel:0x78f14630'1328 28TH ST NORTH'.Height{id: 1580}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f19000'JEFFERSON COUNTY'- AMBIGUOUS LAYOUT for UILabel:0x78f19000'JEFFERSON COUNTY'.minY{id: 1635}, UILabel:0x78f19000'JEFFERSON COUNTY'.Height{id: 1586}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f1b8e0'AL U.S.A'- AMBIGUOUS LAYOUT for UILabel:0x78f1b8e0'AL U.S.A'.minY{id: 1649}, UILabel:0x78f1b8e0'AL U.S.A'.Height{id: 1592}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f191d0'35234'- AMBIGUOUS LAYOUT for UILabel:0x78f191d0'35234'.minY{id: 1642}, UILabel:0x78f191d0'35234'.Height{id: 1598}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f1c0d0'KIRBY MIDDLE SCHOOL'- AMBIGUOUS LAYOUT for UILabel:0x78f1c0d0'KIRBY MIDDLE SCHOOL'.Height{id: 1604}
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f15a80
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f27740
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x78f23120'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   UITableViewCellSelectedBackground:0x78f31ca0
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x787ec8e0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f16570- AMBIGUOUS LAYOUT for UILabel:0x78f16570.minY{id: 1512}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f25b60'801 46TH ST NORTH'- AMBIGUOUS LAYOUT for UILabel:0x78f25b60'801 46TH ST NORTH'.minY{id: 1505}, UILabel:0x78f25b60'801 46TH ST NORTH'.Height{id: 1464}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x787da970'JEFFERSON COUNTY'- AMBIGUOUS LAYOUT for UILabel:0x787da970'JEFFERSON COUNTY'.minY{id: 1519}, UILabel:0x787da970'JEFFERSON COUNTY'.Height{id: 1470}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x78f11fa0'AL U.S.A'- AMBIGUOUS LAYOUT for UILabel:0x78f11fa0'AL U.S.A'.minY{id: 1533}, UILabel:0x78f11fa0'AL U.S.A'.Height{id: 1476}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x787f0ec0'35212'- AMBIGUOUS LAYOUT for UILabel:0x787f0ec0'35212'.minY{id: 1526}, UILabel:0x787f0ec0'35212'.Height{id: 1482}
|   |   |   |   |   |   |   |   |   |   *UILabel:0x787f8910'KINGSTON KINDERG-EIGHTH G...'- AMBIGUOUS LAYOUT for UILabel:0x787f8910'KINGSTON KINDERG-EIGHTH G...'.Height{id: 1488}
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78f1f4c0
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x78727380
|   |   |   |   |   |   |   UIImageView:0x7863a3c0
|   |   |   |   |   |   |   UIImageView:0x7863a950
|   |   |   |   |   |   *UILabel:0x78e0e9d0'Scroll down to find more ...'
|   |   |   |   |   |   *_UILayoutGuide:0x78634c70
|   |   |   |   |   |   *_UILayoutGuide:0x78632b40
|   |   |   UINavigationBar:0x787eecf0
|   |   |   |   _UINavigationBarBackground:0x787caaa0
|   |   |   |   |   UIImageView:0x787ddfa0
|   |   |   |   UIView:0x789096c0
|   |   |   |   UIButton:0x787cb160'#'
|   |   |   |   |   UIButtonLabel:0x7878ebb0'#'
|   |   |   |   UINavigationItemView:0x787faad0'Adding School'
|   |   |   |   |   UILabel:0x7882a2b0'Adding School'
|   |   |   |   _UINavigationBarBackIndicatorView:0x787ebc50


Xcode 6.1.1:

*UIWindow:0x79639930
|   *UITransitionView:0x7ae17cb0
|   |   UILayoutContainerView:0x7965da80
|   |   |   UINavigationTransitionView:0x7ae1abe0
|   |   |   |   UIViewControllerWrapperView:0x7aa313d0
|   |   |   |   |   •UIView:0x7ae17540
|   |   |   |   |   |   *UIImageView:0x796ce990
|   |   |   |   |   |   *UISearchBar:0x7ae179f0
|   |   |   |   |   |   |   UIView:0x796b8710
|   |   |   |   |   |   |   |   UISearchBarBackground:0x796d44b0
|   |   |   |   |   |   |   |   UISearchBarTextField:0x796e5aa0
|   |   |   |   |   |   |   |   |   _UISearchBarSearchFieldBackgroundView:0x7ae1c990
|   |   |   |   |   |   |   |   |   UIFieldEditor:0x7b391c00
|   |   |   |   |   |   |   |   |   |   _UIFieldEditorContentView:0x7a98f600
|   |   |   |   |   |   |   |   |   |   |   UITextSelectionView:0x7ae416b0
|   |   |   |   |   |   |   |   |   |   |   |   UIView:0x7a9d22a0
|   |   |   |   |   |   |   |   |   |   UIImageView:0x7aa210d0
|   |   |   |   |   |   |   |   |   |   UIImageView:0x7aa1af30
|   |   |   |   |   |   |   |   |   UIButton:0x7ae43740
|   |   |   |   |   |   |   |   |   |   UIImageView:0x796f2b50
|   |   |   |   |   |   |   |   |   UIImageView:0x7ae1e9a0
|   |   |   |   |   |   *UILabel:0x7ae242b0'Enter your school name an...'
|   |   |   |   |   |   *UIButton:0x796cb280'Can`t find my school''
|   |   |   |   |   |   |   UIButtonLabel:0x7ae423a0'Can`t find my school''
|   |   |   |   |   |   *UIButton:0x796cdcf0'Find my school'
|   |   |   |   |   |   |   UIButtonLabel:0x7ae41500'Find my school'
|   |   |   |   |   |   *UITableView:0x7b3f0000
|   |   |   |   |   |   |   UITableViewWrapperView:0x7ae1b570
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x7ae55410'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x7ae555f0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae55690
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae55b20'201 COLLEGE ST'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae55ee0'COFFEE COUNTY'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae562f0'AL U.S.A'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae56620'36453'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae56a30'KINSTON SCHOOL'
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7ae57510
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7ae5a5c0
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x7ae50660'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x7ae50840
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae508e0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae50d70'1328 28TH ST NORTH'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae51130'JEFFERSON COUNTY'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae51540'AL U.S.A'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae51870'35234'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae51c80'KIRBY MIDDLE SCHOOL'
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7ae52760
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7974b790
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x7ae3fed0'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x7ae3fac0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae3fb60
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae492c0'125 63RD ST NORTH'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae49640'JEFFERSON COUNTY'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae49a50'AL U.S.A'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae49d80'35212'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae4a190'KENNEDY ALTERNATIVE'
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7ae4ac70
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7ae4e230
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x79600430'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x79600390
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796002a0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7af03150'801 46TH ST NORTH'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7af03510'JEFFERSON COUNTY'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae44720'AL U.S.A'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7a9db7a0'35212'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7ae42ea0'KINGSTON KINDERG-EIGHTH G...'
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7a9e2300
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7ae46110
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x796f7010'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x796f71f0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f7290
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f7720'6077 MAIN ST'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f7ae0'MARSHALL COUNTY'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f7ef0'AL U.S.A'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f8220'35747'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f8630'KATE D SMITH DAR ELEM SCH...'
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x796f9110
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x79602880
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x796ee7f0'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x796ee9d0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796eea70
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f0020'6077 MAIN ST'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796ef5f0'MARSHALL COUNTY'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f0360'AL U.S.A'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796eef70'35747'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f0650'KATE D SMITH DAR HIGH SCH...'
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x796f0840
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x796f4130
|   |   |   |   |   |   |   |   HHSearchSchoolTableViewCell:0x796ea620'com.SearchSchoolCell'
|   |   |   |   |   |   |   |   |   UITableViewCellSelectedBackground:0x7ae48cc0
|   |   |   |   |   |   |   |   |   •UITableViewCellContentView:0x796d68e0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796b1fb0
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796bbff0'6077 MAIN ST'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796f2c70'MARSHALL COUNTY'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x796d93d0'AL U.S.A'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7aa2d3d0'35747'
|   |   |   |   |   |   |   |   |   |   *UILabel:0x7aa2d5b0'KATE DUNCAN SMITH DAR MID...'
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x7aa2d670
|   |   |   |   |   |   |   |   |   _UITableViewCellSeparatorView:0x796eb0d0
|   |   |   |   |   |   |   UIImageView:0x7ae1fd50
|   |   |   |   |   |   |   UIImageView:0x7ae205c0
|   |   |   |   |   |   *UILabel:0x7ae23460'Scroll down to find more ...'
|   |   |   |   |   |   *_UILayoutGuide:0x7ae175e0
|   |   |   |   |   |   *_UILayoutGuide:0x7ae177f0
|   |   |   UINavigationBar:0x796cca90
|   |   |   |   _UINavigationBarBackground:0x796a8f20
|   |   |   |   |   UIImageView:0x796c8270
|   |   |   |   UIView:0x7ae24a90
|   |   |   |   UIButton:0x7ae21d50'#'
|   |   |   |   |   UIButtonLabel:0x7ae2ade0'#'
|   |   |   |   UINavigationItemView:0x796da5a0'Adding School'
|   |   |   |   |   UILabel:0x796b7710'Adding School'
|   |   |   |   _UINavigationBarBackIndicatorView:0x796cdc10

**Comment by smileyborg** [comment] 2015-04-25 23:18
@hamdan If you see issues on the iOS Simulator but **not** on the device, then this is almost certainly Apple's bug, and you should file a bug report with them: http://bugreport.apple.com If you're certain this is only reproducible in the Simulator, I would not worry much about it because obviously real users only run your app on real devices.

Unfortunately, sharing a small piece of your code and a view hierarchy dump is not enough for me to be able to reproduce the issue or identify exactly what might be the problem. So you'll need to provide exact steps on how to reproduce this issue and/or share a sample project that does so, if you would like me to help investigate further.

I don't have any reason to believe this is an issue related to PureLayout at this time, and without the additional information I have requested, I am unable help you or @ryderjack here. So I am closing this issue for now.

**Closed by smileyborg** 2015-04-25 23:18 UTC
