### ISSUE TITLE
Demo App Constraint Conflict

### ISSUE THREAD

**Issue by emiscience** [smileyborg/PureLayout#67] opened 2015-05-27 20:21 UTC
Hi,

I've played around with the demo app a while and came up with a constraint conflict/vioulation..

Here's the exact debugger output:

   `Set the NSUserDefault NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints to YES to have -[NSWindow visualizeConstraints:] automatically called when this happens.  And/or, break on objc_exception_throw to catch this in the debugger.`

I've taken a screen-recording so you can see what I was up to...

https://dl.dropboxusercontent.com/u/61211034/PureLayout%20-%20Constratint%20Conflict.mov

When I get some time I'll shove the NSUSerdefaults on and see whats happening.

By the looks of how it goes, it seems like the minimum height is surpassed.. Will update soon.

Cheers,

A

**Comment by emiscience** [comment] 2015-05-27 20:32
Actually this happens on quite a few of the demo's.. The only one of the lot that seems to keep it's minimum's is demo2's widths..

Here are my findings:

Mac: Demo1 - Width, exceeded, constraints not broken, Height: expands as "horizontal spacing between top and bottom neighbours decreases" then constraints break.
Mac: Demo 2: Height: no change, constraints broken on zero (or there about), width: Object height and width changes accordingly, doesn't allow to pass minimum width. No broken constraints *this is the only workingmen I found*
Mac Demo 3: Height: Orange resizes accordingly, but when orange is less than zero, broken constraints. Width: All resize accordingly, and in aspect. When orange reaches zero width, constraints broken. (not sure about the others)
Mac Demo 4: Width: Non od the objects change, minimum width reached about 80% of the size of orange. No broken constraints. Height: Nothing resizes. When window frame borrow reaches orange, constraints broken.

Sorry to bring you the bad news! Great work tho! I'm looking through it to see how portable it is to swift. Keep up the amazing coding!

Cheers

Adrian from kent

**Comment by smileyborg** [comment] 2015-05-29 19:21
Hi Adrian,

Thanks for bringing this up. Based on the video, it looks like what you are doing is "excessively" resizing the window to extremely small widths/heights. The constraints in these demos are assuming that the window will not be resized below some realistic minimum, small size.

So the fact that you get broken constraints and what not is actually expected behavior :) The "fix" for this is really just to implement a minimum size for the window on the Mac demo app, to prevent the user from resizing the window to be unreasonably small -- if you would like to do this, I would appreciate a pull request!

Also, as far as [this image](http://i60.tinypic.com/2808qjd.jpg), I am not sure what you are suggesting the problem is? (If you are concerned about the text clipping in the orange view, that is expected behavior based on the constraints.)

**Comment by smileyborg** [comment] 2015-05-29 19:24
Also, since you mentioned Swift, just wanted to point out that the current Obj-C library works great bridged into Swift as it currently stands. I don't think a pure Swift port would be a good idea; if you are working in pure Swift you can do even more than what's possible in Objective-C...for example, I would recommend you take a look at [Cartography](https://github.com/robb/Cartography).

**Comment by smileyborg** [comment] 2015-06-05 03:42
Closing for now, please let me know if you think there are other issues beyond what I have addressed above.

**Closed by smileyborg** 2015-06-05 03:42 UTC
