### ISSUE TITLE
ALAxisVertical refers to horizontal centerX

### ISSUE THREAD

**Issue by pronebird** [smileyborg/PureLayout#60] opened 2015-04-09 11:05 UTC
`centerX` is really a horizontal axis isn't it? It's confusing.

```objc
[self.view1 autoAlignAxis:ALAxisVertical toSameAxisOfView:self.view2];
```

This in fact produces: 

```ruby
view1.centerX == view2.centerX
```

When I use lldb I query for horizontal axis to see that constraint:

```ruby
po [self.view1 constraintsAffectingLayoutForAxis:UILayoutConstraintAxisHorizontal]
```

**Comment by smileyborg** [comment] 2015-04-09 15:39
Hey Andrei,

This is a duplicate of #33. There's either a slight misunderstanding of how the `ALAxis` attributes are defined, and/or the method names are being overlooked.

Asking for the constraints that affect a view's layout in the horizontal axis is completely different from saying that you want to align the vertical axis of two views. Don't get confused that using `ALAxisVertical` to align 2 views will end up creating constraints that work along the horizontal axis.

**Closed by smileyborg** 2015-04-09 15:39 UTC
